### ISSUE TITLE
SES Provider

### ISSUE THREAD

**Issue by woutercouvaras** [parse-community/parse-server-api-mail-adapter#64]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/mtrezza/parse-server-api-mail-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/mtrezza/parse-server-api-mail-adapter#need-help).
- [x] I have searched through [existing issues](https://github.com/mtrezza/parse-server-api-mail-adapter/issues?q=is%3Aissue).

### Current Limitation

I love the design of this module.  Because of the smart design, running a custom provider is pretty easy, but I was wondering if you would like an SES converter?  I've already built it and updated docs and ready to do a PR.

### Feature / Enhancement Description

Simply adding an SES Payload Converter, with additions to docs to explain useage.

### Example Use Case

Sending system emails via AWS SES.

### Alternatives / Workarounds

The custom api support it totaly viable, so this is not strictly necessary, I just thought it might be nice to bake it into the package, but that could create additional noise, so I'm totally happy if you shut this down :D

### 3rd Party References

No really applicable, I don't think?

**Comment by mtrezza** [comment]
Amazing, let's add the payload converter. Could you like the PR?

**Comment by woutercouvaras** [comment]
Just created the PR:  https://github.com/parse-community/parse-server-api-mail-adapter/pull/65

I'm a noob to contributing to open source, happy to learn and tow the line :)
