### ISSUE TITLE
apiPayloadConverter doesn't have the awsSes method

### ISSUE THREAD

**Issue by andreisucman** [parse-community/parse-server-api-mail-adapter#71]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/mtrezza/parse-server-api-mail-adapter/security/policy).
- [ ] I am not just asking a [question](https://github.com/mtrezza/parse-server-api-mail-adapter#need-help).
- [x] I have searched through [existing issues](https://github.com/mtrezza/parse-server-api-mail-adapter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version](https://github.com/mtrezza/parse-server-api-mail-adapter/releases). 

### Issue Description
The adapter uses the ApiPayloadConverter.awsSes(payload) method in the apiCallback function, which gives the ApiPayloadConverter.awsSes is not a function error. After inspecting the ApiPayloadConverter.js in the src folder I saw that it has only the mailgun method. So either the awsSes method should be added or the documentation should be corrected.

### Expected Outcome
I expected the module to work with AWS SES

###  Environment

- API Mail Adapter version: `2.1.0`
- Parse Server version: `5.3.3`

**Comment by andreisucman** [comment]
I now checked the src folder on Git Hub and can see it there, but not in the node modules.

**Comment by mtrezza** [comment]
Closing as feature just hasn't been released as stable version yet.

**Comment by mtrezza** [comment]
@andreisucman We have released version 2.2.0. Just so you know, even if a commit is only on the alpha branch, it is published as a pre-release to npm. In other words, you can use `parse-server-api-mail-adapter@2.2.0-alpha.1` for example to point to the alpha version.
