### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by tbjers** [parse-community/parse-server-api-mail-adapter#89]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/mtrezza/parse-server-api-mail-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/mtrezza/parse-server-api-mail-adapter#need-help).
- [x] I have searched through [existing issues](https://github.com/mtrezza/parse-server-api-mail-adapter/issues?q=is%3Aissue).

### Current Limitation

Type declaration comments are stripped out by Babel.

### Feature / Enhancement Description

Add TypeScript definition files as outlined in [Creating .d.ts Files from .js files](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) in the TypeScript documentation.

### Example Use Case

1. Add type definitions to `lib/` directory.
2. Update `build` step in `package.json` with `&& tsc`.
3. Definitions will be included when publishing the package.
4. Rejoice.

### Alternatives / Workarounds

No alternatives or workarounds exist.

### 3rd Party References

There is no `@types/parse-server-api-mail-adapter` package.

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.1.0](https://github.com/parse-community/parse-server-api-mail-adapter/releases/tag/3.1.0)
