### ISSUE TITLE
Add ZeptoMail support

### ISSUE THREAD

**Issue by ashish-naik** [parse-community/parse-server-api-mail-adapter#97]
- [x] I am not disclosing a [vulnerability](https://github.com/mtrezza/parse-server-api-mail-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/mtrezza/parse-server-api-mail-adapter#need-help).
- [x] I have searched through [existing issues](https://github.com/mtrezza/parse-server-api-mail-adapter/issues?q=is%3Aissue).

### Current Limitation
ZeptoMail support is not available.

### Feature / Enhancement Description
Payload converter will have a method to convert payload to ZeptoMail format

### Example Use Case
Same use case as applicable to AWS SES or Mailgun

### Alternatives / Workarounds
none 

### 3rd Party References
Do not know.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0](https://github.com/parse-community/parse-server-api-mail-adapter/releases/tag/4.1.0)
